### PR TITLE
Fix for Cursor moving to the end of input when editing the phonenumbe…

### PR DESCRIPTION
**Pull request by mohammedzamakhan**
…r in between

### CODE REVIEW

**Comment by cwill747** [comment]
Hey @zamamohammed your changes actually need to go in src/phone-number.js. The dist/ files are built, and your changes would be overwritten. Then you can run gulp to build the package.

**Comment by mohammedzamakhan** [comment]
Done :+1:

**Comment by mohammedzamakhan** [comment]
@cwill747 I do not know why the test is failing.

**Comment by cwill747** [comment]
Looks like an issue with the build system... I'll take a look

**Comment by mohammedzamakhan** [comment]
@cwill747 I am unable to pull this change using bower, let me know when I should be able to pull it :+1: 

Thanks a lot

**Comment by cwill747** [comment]
Hey the change has caused two tests to fail. Before I push a new bower version I need to find out if the tests need to be updated or if the code does. In the meantime, you can depend on the git version of the code if you understand the risks:

``` javascript
{
  dependencies: [
       "angular-libphonenumber": "https://github.com/cwill747/angular-libphonenumber.git"
  ]
}
```

**Pull request merged**
