### PR TITLE
fix: trim formatted value to fix backspacing problem

### PR DESCRIPTION
**Pull request by dbaq**
assigned #8

### CODE REVIEW

**Comment by cwill747** [comment]
Hey @dbaq can you also run "gulp" locally and check in the dist files as well? I'll add that to the contributing guidelines. In your next commit, I also need your acceptance of the DCO. Instructions are [here in CONTRIBUTING.md](CONTRIBUTING.md#footer)

**Comment by dbaq** [comment]
hey @cwill747 I updated my commit. Running the tests via `gulp` is not working properly:

```
[08:23:43] Finished 'serve' after 129 ms
Server running in port 8000
INFO [Chrome 47.0.2526 (Mac OS X 10.11.0)]: Connected on socket -pwyQrzYl9sloBzgJgQ0 with id 52192570
Chrome 47.0.2526 (Mac OS X 10.11.0) ERROR
  Uncaught ReferenceError: angular is not defined
  at /Users/dbaq/angular/angular-libphonenumber/src/phone-number.js:9


[08:23:45] 'test:unit' errored after 3.43 s
[08:23:45] Error: 1
  at formatError (/Users/dbaq/.node/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/Users/dbaq/.node/lib/node_modules/gulp/bin/gulp.js:195:15)
  at emitOne (events.js:77:13)
  at Gulp.emit (events.js:169:7)
  at Gulp.Orchestrator._emitTaskDone (/Users/dbaq/angular/angular-libphonenumber/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/dbaq/angular/angular-libphonenumber/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/dbaq/angular/angular-libphonenumber/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/dbaq/angular/angular-libphonenumber/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at removeAllListeners (/Users/dbaq/angular/angular-libphonenumber/node_modules/karma/lib/server.js:220:7)
  at Server.<anonymous> (/Users/dbaq/angular/angular-libphonenumber/node_modules/karma/lib/server.js:231:9)
  at Server.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Server.emit (events.js:166:7)
  at emitCloseNT (net.js:1521:8)
  at doNTCallback1 (node.js:428:9)
  at process._tickCallback (node.js:350:17)

chromedriver_2.19.zip downloaded to /Users/dbaq/angular/angular-libphonenumber/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver_2.19.zip
selenium-server-standalone-2.47.1.jar downloaded to /Users/dbaq/angular/angular-libphonenumber/node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
[08:23:49] Finished 'webdriver_update' after 7.47 s
```

any idea what I am doing wrong? Thanks

**Comment by cwill747** [comment]
Did you run `bower install` and `npm install` before running `gulp`?

**Comment by dbaq** [comment]
My bad I was missing the `bower install`. The tests are ok.

```
Finished in 4.407 seconds
3 tests, 48 assertions, 0 failures

[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

**Pull request merged**
